name: Check for broken links
on: [deployment_status]
jobs:
  checklinks:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Find all MDX files
      id: findmdx
      run: |
        mdx_files=$(find pages -name '*.mdx' | tr '\n' ' ')
        echo "Found MDX files: $mdx_files"
        echo "::set-output name=mdxfiles::$mdx_files"
    - name: Link Checker
      uses: hashicorp/gh-action-check-broken-links@v1
      with:
        baseUrl: ${{ github.event.deployment_status.target_url }}
        files: ${{ steps.findmdx.outputs.mdxfiles }}
        whitelist: |
          https://youtube.com/
          https://youtu.be
          https://loom.com
